config/routes.rb
Rails.application.routes.draw do
  
  get 'login', to: 'sessions#new' # Vista
  post 'login', to: 'sessions#create' # Quien procesa la petició!

  get 'logout', to: 'sessions#destroy'

  root 'main#home'
  get 'custome', to: 'main#custome'

  resources :users, only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user
    helper_method :user_authenticated?

    def current_user
        User.find session[:user_id] if session[:user_id]
    end

    def user_authenticated?
        !current_user.nil?
    end

    def authorized!
        return redirect_to login_path unless user_authenticated?
    end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  before_action :authorized!, only: [:custome]
  
  def home
  end

  def custome
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    @user = User.find_by username: params[:username]

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id

      return redirect_to root_path
    end

    redirect_to login_path

  end

  def destroy
    session[:user_id] = nil

    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.create(
      params.require(:user).permit(:username, :password)
    )

    session[:user_id] = @user.id

    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>CódigoFacilito Live</title>
  </head>
  <body>
    
    <div class="container">
      <div class="row">
        <div class="col">
            <%= yield %>
        </div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    
  </body>
</html>

app/views/main/home.html.erb
<div class="row">
    <div class="col">
        <h1>Bienvenidos</h1>
    </div>
</div>

<hr>

<% if user_authenticated? %>
    <div class="row">
        <div class="col">
            <div>
                <%= link_to 'Logout', logout_path %>
            </div>
        </div>
    </div>
<% else %>
    <div class="row">
        <div class="col">
            <div>
                <%= link_to 'Crear cuenta', new_user_path %>
            </div>
        </div>
    </div>
<% end %>

<%= link_to 'Custome', custome_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="row mt-2">   
    <div class="col">
        <h3>Nuevo usuario</h3>
        <%= form_for @user do |user| %>
            
            <div class="form-group">
                Username:
                <%= user.text_field :username, class:'form-control' %>
            </div>

            <div class="form-group">
                Password:
                <%= user.password_field :password, class:'form-control' %>
            </div>
            
            <input type="submit" value="Crear usuario", class="btn btn-primary">

        <% end %>
    </div>
</div>